backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{path}}”'
    update: 'Update {{collection}} “{{path}}”'
    delete: 'Delete {{collection}} “{{path}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: /static/assets/
public_folder: /assets/

collections:
  - name: "posts"
    label: "Posts"
    folder: "/content/posts/"
    create: true
    fields:
      - { name: "path", label: "Slug" }
      - { name: "date", label: "Published Date", widget: "datetime" }
      - { name: "title", label: "Title" }
      - { name: "body", label: "Introduction", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "cover", label: "Featured Image", widget: "image", required: true }
      - label: "Upper Gallery"
        name: "upperGalleryImages"
        widget: "object"
        fields:
          - {label: Image 1, name: image1, widget: image, required: true}
          - {label: Image 2, name: image2, widget: image, required: true}
          - {label: Image 3, name: image3, widget: image, required: true}
          - {label: Image 4, name: image4, widget: image, required: true}
      - label: "Text sections"
        name: "textSections"
        widget: "list"
        allow_add: true
        collapsed: false
        fields:
          - {label: Title, name: textTitle, widget: "string", default: "Title here", required: true}
          - {label: Text, name: text, widget: markdown, default: "Body text here", required: true}
          - label: "Side Gallery"
            name: "sideGalleryImages"
            widget: "list"
            allow_add: true
            collapsed: true
            field: {label: Image, name: image, widget: image}
  - name: "maps"
    label: "Maps"
    folder: "/content/maps/"
    create: true
    fields:
      - { name: "path", label: "Path" }
      - { name: "title", label: "Title" }
      - { name: "googleApi", label: "Google API URL"}
      - { name: "tags", label: "Tags", widget: "list" }