export { default as Footer } from './Footer'
export { default as Layout } from './Layout'
export { default as Navbar } from './Navbar'
export { default as Newsletter } from './Newsletter'
export { default as SearchResults } from './SearchResults'
